# Generated by Django 4.0.3 on 2022-05-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('view', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('type', models.CharField(max_length=70, verbose_name='Тип темы')),
                ('round', models.PositiveIntegerField(verbose_name='Раунд')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок темы')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigame.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость вопроса')),
                ('description', models.TextField(verbose_name='Вопроc')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigame.subject', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
